/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/*import static com.sun.xml.internal.fastinfoset.alphabet.BuiltInRestrictedAlphabets.table;*/
import java.awt.CardLayout;
import java.awt.event.*;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
/**Mantenimiento**/
import vista.*;
/*Hora y fehca*/
import java.util.Date;
import java.util.Calendar;
import javax.swing.Timer;

/**/
/**
 *
 * @author cbhzito
 */
public class VMenuPrincipal extends javax.swing.JFrame{

    DefaultTableModel modVenta = new DefaultTableModel();

    public VMenuPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("SISTEMA DE VENTAS");
        this.setResizable(false);
        tablaRVenta();
        /*Fecha auto*/
        lblFechaAuto.setText(fechaAuto());
        /*Hora auto*/
        Timer tiempo = new Timer(100, new VMenuPrincipal.Hora());
        tiempo.start();
    }
    class Hora implements ActionListener {
        
        @Override
        public void actionPerformed(ActionEvent e) {
            Date sistHora = new Date();
            String amPM = "hh:mm:ss a";
            SimpleDateFormat format = new SimpleDateFormat(amPM);
            Calendar hoy = Calendar.getInstance();
            lblHoraAuto.setText(String.format(format.format(sistHora), hoy));
        }
        
    }
    public void tablaRVenta() {

        String ar[] = {"PRODUCTO", "PRECIO", "CANTIDAD", "IMPORTE"};
        modVenta.setColumnIdentifiers(ar);
        jTable1.setModel(modVenta);

        TableColumnModel columnModel = jTable1.getColumnModel();

        columnModel.getColumn(0).setPreferredWidth(500);
        columnModel.getColumn(1).setPreferredWidth(150);
        columnModel.getColumn(2).setPreferredWidth(150);
        columnModel.getColumn(3).setPreferredWidth(150);
    }

    /**
     * FECHA AUTOMATICA*
     */
    public static String fechaAuto() {
        Date fecha = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MMM/YYYY");
        return sdf.format(fecha);
    }
    /*Hora auto*/
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpFondo = new javax.swing.JPanel();
        jpTitulo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lblHoraAuto = new javax.swing.JLabel();
        lblFechaAuto = new javax.swing.JLabel();
        jpBarraMenu = new javax.swing.JPanel();
        lblTipoEmpleado = new javax.swing.JLabel();
        jpMenus = new javax.swing.JPanel();
        btnMVenta = new javax.swing.JButton();
        btnMCompras = new javax.swing.JButton();
        btnMReportes = new javax.swing.JButton();
        btnMMantenimiento = new javax.swing.JButton();
        lblCopy2 = new javax.swing.JLabel();
        lblCopy1 = new javax.swing.JLabel();
        jpMenusCards = new javax.swing.JPanel();
        jpVentas = new javax.swing.JPanel();
        jpRegistrarVenta = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        lblNBoleta = new javax.swing.JLabel();
        jpBuscarProducto = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        txtNombreProducto = new javax.swing.JTextField();
        btnBuscarProducto = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        txtStockPro = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        txtPrecioProd = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        btnAgregarProducto = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSpinner1 = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jpBuscarCliente = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        txtNombreCliente = new javax.swing.JTextField();
        btnBuscarCliente = new javax.swing.JButton();
        btnRegistrarVenta = new javax.swing.JButton();
        btnRegistrarVenta2 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        txtMontoTotal = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        btnQuitarProducto = new javax.swing.JButton();
        jpCompras = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton14 = new javax.swing.JButton();
        jSpinner2 = new javax.swing.JSpinner();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jButton13 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        txtMontoTotal1 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jpReportes = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jpVerVentas = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jdcDesde = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jdcHasta = new com.toedter.calendar.JDateChooser();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable7 = new javax.swing.JTable();
        btnImpV = new javax.swing.JButton();
        jpVerCompras = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jdcDesde1 = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jdcHasta1 = new com.toedter.calendar.JDateChooser();
        btnImpC = new javax.swing.JButton();
        jpVerClientes = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        btnImpV3 = new javax.swing.JButton();
        jpVerProductos = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        btnImpp = new javax.swing.JButton();
        jpMantenimiento = new javax.swing.JPanel();
        jpClientes = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblCantClientes = new javax.swing.JLabel();
        btnEntrarClientes = new javax.swing.JButton();
        jpProductos = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        lblCantProductos = new javax.swing.JLabel();
        btnEntrarProductos = new javax.swing.JButton();
        jpUsuarios = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        lblCantUsuarios = new javax.swing.JLabel();
        btnEntrarUsuario = new javax.swing.JButton();
        jpProveedores = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblCantProveedores = new javax.swing.JLabel();
        btnEntrarProveedor = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1300, 700));
        setMinimumSize(new java.awt.Dimension(1300, 700));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1300, 700));
        setResizable(false);
        setSize(new java.awt.Dimension(1300, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpFondo.setBackground(new java.awt.Color(255, 255, 255));
        jpFondo.setMaximumSize(new java.awt.Dimension(1300, 690));
        jpFondo.setMinimumSize(new java.awt.Dimension(1300, 690));
        jpFondo.setName(""); // NOI18N
        jpFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpTitulo.setBackground(new java.awt.Color(0, 51, 51));
        jpTitulo.setMaximumSize(new java.awt.Dimension(1180, 80));
        jpTitulo.setPreferredSize(new java.awt.Dimension(1180, 90));
        jpTitulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 46)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("BODEGA \"MADYSON\"");
        jpTitulo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 500, 60));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("HORA:");
        jpTitulo.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 30, 90, 20));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("FECHA:");
        jpTitulo.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 30, 100, 20));

        lblHoraAuto.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblHoraAuto.setForeground(new java.awt.Color(255, 255, 255));
        lblHoraAuto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHoraAuto.setText("00 : 00 : 00");
        jpTitulo.add(lblHoraAuto, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 30, 150, 20));

        lblFechaAuto.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblFechaAuto.setForeground(new java.awt.Color(255, 255, 255));
        lblFechaAuto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFechaAuto.setText("DD/MM/YYYY");
        jpTitulo.add(lblFechaAuto, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 30, 140, 20));

        jpFondo.add(jpTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 80));

        jpBarraMenu.setBackground(new java.awt.Color(51, 51, 51));
        jpBarraMenu.setMaximumSize(new java.awt.Dimension(240, 570));
        jpBarraMenu.setMinimumSize(new java.awt.Dimension(240, 570));
        jpBarraMenu.setPreferredSize(new java.awt.Dimension(240, 570));
        jpBarraMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTipoEmpleado.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTipoEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        lblTipoEmpleado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTipoEmpleado.setText("ADMINISTRADOR");
        jpBarraMenu.add(lblTipoEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 220, 50));

        jpMenus.setBackground(new java.awt.Color(204, 204, 204));

        btnMVenta.setBackground(new java.awt.Color(255, 255, 255));
        btnMVenta.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnMVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/venta40x40.png"))); // NOI18N
        btnMVenta.setText("                  VENTA");
        btnMVenta.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnMVenta.setPreferredSize(new java.awt.Dimension(220, 60));
        btnMVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMVentaActionPerformed(evt);
            }
        });
        jpMenus.add(btnMVenta);

        btnMCompras.setBackground(new java.awt.Color(255, 255, 255));
        btnMCompras.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnMCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/compra40x40.png"))); // NOI18N
        btnMCompras.setText("               COMPRA");
        btnMCompras.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnMCompras.setPreferredSize(new java.awt.Dimension(220, 60));
        btnMCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMComprasActionPerformed(evt);
            }
        });
        jpMenus.add(btnMCompras);

        btnMReportes.setBackground(new java.awt.Color(255, 255, 255));
        btnMReportes.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnMReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/reporte40x40.png"))); // NOI18N
        btnMReportes.setText("           REPORTES");
        btnMReportes.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnMReportes.setPreferredSize(new java.awt.Dimension(220, 60));
        btnMReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMReportesActionPerformed(evt);
            }
        });
        jpMenus.add(btnMReportes);

        btnMMantenimiento.setBackground(new java.awt.Color(255, 255, 255));
        btnMMantenimiento.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnMMantenimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/mantenimiento40x40.png"))); // NOI18N
        btnMMantenimiento.setText(" MANTENIMIENTO");
        btnMMantenimiento.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnMMantenimiento.setPreferredSize(new java.awt.Dimension(220, 60));
        btnMMantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMMantenimientoActionPerformed(evt);
            }
        });
        jpMenus.add(btnMMantenimiento);

        jpBarraMenu.add(jpMenus, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 240, 470));

        lblCopy2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCopy2.setForeground(new java.awt.Color(255, 255, 255));
        lblCopy2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCopy2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblCopy2.setMaximumSize(new java.awt.Dimension(220, 20));
        lblCopy2.setMinimumSize(new java.awt.Dimension(220, 20));
        lblCopy2.setPreferredSize(new java.awt.Dimension(220, 20));
        jpBarraMenu.add(lblCopy2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 570, 220, 20));

        lblCopy1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCopy1.setForeground(new java.awt.Color(255, 255, 255));
        lblCopy1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCopy1.setText("2018");
        lblCopy1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblCopy1.setMaximumSize(new java.awt.Dimension(220, 20));
        lblCopy1.setMinimumSize(new java.awt.Dimension(220, 20));
        lblCopy1.setPreferredSize(new java.awt.Dimension(220, 20));
        jpBarraMenu.add(lblCopy1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 220, 20));

        jpFondo.add(jpBarraMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 240, 600));

        jpMenusCards.setLayout(new java.awt.CardLayout());

        jpVentas.setBackground(new java.awt.Color(255, 255, 255));
        jpVentas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpRegistrarVenta.setBackground(new java.awt.Color(255, 255, 255));
        jpRegistrarVenta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel14.setText("N° DE BOLETA:");
        jpRegistrarVenta.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, 30));

        lblNBoleta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNBoleta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNBoleta.setText("000 000 001");
        lblNBoleta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jpRegistrarVenta.add(lblNBoleta, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 23, 220, 30));

        jpBuscarProducto.setBackground(new java.awt.Color(255, 255, 255));
        jpBuscarProducto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "BÚSQUEDA DE PRODUCTO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N
        jpBuscarProducto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel26.setText("CANTIDAD:");
        jpBuscarProducto.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, 30));

        txtNombreProducto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jpBuscarProducto.add(txtNombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 310, 25));

        btnBuscarProducto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBuscarProducto.setText("BUSCAR");
        btnBuscarProducto.setMaximumSize(new java.awt.Dimension(180, 50));
        btnBuscarProducto.setMinimumSize(new java.awt.Dimension(180, 50));
        btnBuscarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProductoActionPerformed(evt);
            }
        });
        jpBuscarProducto.add(btnBuscarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 100, 30));

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel28.setText("NOMBRE DEL PRODUCTO:");
        jpBuscarProducto.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 150, 20));

        txtStockPro.setEditable(false);
        txtStockPro.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtStockPro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jpBuscarProducto.add(txtStockPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 60, 25));

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel29.setText("PRECIO: S/");
        jpBuscarProducto.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 70, 20));

        txtPrecioProd.setEditable(false);
        txtPrecioProd.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtPrecioProd.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jpBuscarProducto.add(txtPrecioProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 80, 25));

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel30.setText("STOCK:");
        jpBuscarProducto.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 60, 20));

        btnAgregarProducto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAgregarProducto.setText("AGREGAR");
        btnAgregarProducto.setMaximumSize(new java.awt.Dimension(180, 50));
        btnAgregarProducto.setMinimumSize(new java.awt.Dimension(180, 50));
        jpBuscarProducto.add(btnAgregarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 110, 30));
        jpBuscarProducto.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 460, 10));
        jpBuscarProducto.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 70, 30));

        jpRegistrarVenta.add(jpBuscarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(497, 53, 520, 210));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Producto", "Precio", "Cantidad", "Importe"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jpRegistrarVenta.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 304, 770, 260));

        jpBuscarCliente.setBackground(new java.awt.Color(255, 255, 255));
        jpBuscarCliente.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "BÚSQUEDA DEL CLIENTE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N
        jpBuscarCliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("NOMBRE DEL CLIENTE:");
        jpBuscarCliente.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 220, -1));

        txtNombreCliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jpBuscarCliente.add(txtNombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 300, 25));

        btnBuscarCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBuscarCliente.setText("BUSCAR");
        btnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteActionPerformed(evt);
            }
        });
        jpBuscarCliente.add(btnBuscarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, -1, -1));

        jpRegistrarVenta.add(jpBuscarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 144, 440, 119));

        btnRegistrarVenta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnRegistrarVenta.setText("REGISTRAR VENTA");
        btnRegistrarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarVentaActionPerformed(evt);
            }
        });
        jpRegistrarVenta.add(btnRegistrarVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 360, 160, 50));

        btnRegistrarVenta2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnRegistrarVenta2.setText("IMPRIMIR BOLETA");
        btnRegistrarVenta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarVenta2ActionPerformed(evt);
            }
        });
        jpRegistrarVenta.add(btnRegistrarVenta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 420, 160, 40));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("MONTO FINAL:");
        jpRegistrarVenta.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 490, 160, -1));

        txtMontoTotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtMontoTotal.setForeground(new java.awt.Color(255, 0, 0));
        txtMontoTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMontoTotal.setText("S/ ");
        txtMontoTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jpRegistrarVenta.add(txtMontoTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 510, 160, 50));

        jLabel37.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel37.setText("SELECCIONAR FECHA:");
        jpRegistrarVenta.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 80, 160, 30));
        jpRegistrarVenta.add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 220, 25));

        btnQuitarProducto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnQuitarProducto.setText("QUITAR PEDIDO");
        btnQuitarProducto.setMaximumSize(new java.awt.Dimension(180, 50));
        btnQuitarProducto.setMinimumSize(new java.awt.Dimension(180, 50));
        jpRegistrarVenta.add(btnQuitarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 310, 160, 40));

        jpVentas.add(jpRegistrarVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jpMenusCards.add(jpVentas, "card3");

        jpCompras.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)), "SELECCIONAR PROVEEDOR", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18))); // NOI18N
        jPanel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel16.setText("NOMBRE DEL PROVEEDOR:");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));
        jPanel4.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 271, 25));

        jLabel24.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel24.setText("R.U.C. :");
        jPanel4.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("BUSCAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, -1, 29));

        jTextField4.setVerifyInputWhenFocusTarget(false);
        jPanel4.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 271, 25));

        jpCompras.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 430, 170));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)), "AGREGAR PRODUCTOS\n", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18))); // NOI18N
        jPanel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel31.setText("NOMBRE DEL PRODUCTO:");
        jPanel2.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 41, -1, -1));
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 68, 330, 25));

        jLabel32.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel32.setText("INGRESAR CANTIDAD:");
        jPanel2.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 160, -1, -1));

        jButton12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton12.setText("BUSCAR");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 64, -1, 29));

        jLabel33.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel33.setText("PRECIO COMPRA:");
        jPanel2.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 114, 143, 25));
        jPanel2.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 114, 91, 25));

        jButton14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton14.setText("AGREGAR");
        jPanel2.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 109, 34));
        jPanel2.add(jSpinner2, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 157, 46, 25));

        jpCompras.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, 510, 210));

        jTable6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 1, true));
        jTable6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PROVEEDOR", "PRODUCTO", "PRECIO", "CANTIDAD", "IMPORTE"
            }
        ));
        jScrollPane6.setViewportView(jTable6);

        jpCompras.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 770, 260));

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel34.setText("N° DE BOLETA:");
        jpCompras.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jLabel35.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel35.setText("SELECCIONAR FECHA:");
        jpCompras.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, -1, 30));
        jpCompras.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 20, 220, 25));

        jButton13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton13.setText("REGISTRAR COMPRA");
        jpCompras.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 370, 170, 40));

        jButton15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton15.setText("QUITAR PEDIDO");
        jpCompras.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 310, 170, 40));

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setText("MONTO FINAL:");
        jpCompras.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 500, 160, -1));

        txtMontoTotal1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtMontoTotal1.setForeground(new java.awt.Color(255, 0, 0));
        txtMontoTotal1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMontoTotal1.setText("S/ ");
        txtMontoTotal1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jpCompras.add(txtMontoTotal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 520, 160, 50));

        jTextField5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jpCompras.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 210, 30));

        jpMenusCards.add(jpCompras, "card5");

        jpReportes.setBackground(new java.awt.Color(255, 255, 255));
        jpReportes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane2.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane2.setForeground(new java.awt.Color(0, 0, 51));
        jTabbedPane2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jpVerVentas.setBackground(new java.awt.Color(255, 255, 255));
        jpVerVentas.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jpVerVentas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setText("AYER");
        jButton1.setPreferredSize(new java.awt.Dimension(100, 40));
        jPanel3.add(jButton1);

        jButton2.setText("HOY");
        jButton2.setPreferredSize(new java.awt.Dimension(100, 40));
        jPanel3.add(jButton2);

        jButton5.setText("ELEGIR FECHA");
        jButton5.setPreferredSize(new java.awt.Dimension(150, 40));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5);

        jLabel9.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel3.add(jLabel9);

        jLabel4.setText("DESDE: ");
        jPanel3.add(jLabel4);

        jdcDesde.setEnabled(false);
        jdcDesde.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jdcDesde.setPreferredSize(new java.awt.Dimension(120, 25));
        jPanel3.add(jdcDesde);

        jLabel7.setPreferredSize(new java.awt.Dimension(100, 0));
        jPanel3.add(jLabel7);

        jLabel8.setText("HASTA: ");
        jPanel3.add(jLabel8);

        jdcHasta.setEnabled(false);
        jdcHasta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jdcHasta.setPreferredSize(new java.awt.Dimension(120, 25));
        jPanel3.add(jdcHasta);

        jpVerVentas.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 950, 50));

        jTable7.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N° VENTA", "CLIENTE", "VENDEDOR", "FECHA", "CANTIDAD", "TOTAL"
            }
        ));
        jScrollPane7.setViewportView(jTable7);

        jpVerVentas.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 116, 950, 380));

        btnImpV.setText("IMPRIMIR");
        jpVerVentas.add(btnImpV, new org.netbeans.lib.awtextra.AbsoluteConstraints(853, 513, 150, 30));

        jTabbedPane2.addTab("VER VENTAS  ", new javax.swing.ImageIcon(getClass().getResource("/iconos/bolsa-de-la-compra.png")), jpVerVentas); // NOI18N

        jpVerCompras.setBackground(new java.awt.Color(255, 255, 255));
        jpVerCompras.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N° COMPRA", "FECHA", "PROVEEDOR", "CANTIDAD", "TOTAL"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jpVerCompras.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 116, 950, 390));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jButton9.setText("AYER");
        jButton9.setPreferredSize(new java.awt.Dimension(100, 40));
        jPanel7.add(jButton9);

        jButton10.setText("HOY");
        jButton10.setPreferredSize(new java.awt.Dimension(100, 40));
        jPanel7.add(jButton10);

        jButton11.setText("ELEGIR FECHA");
        jButton11.setPreferredSize(new java.awt.Dimension(150, 40));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton11);

        jLabel10.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel7.add(jLabel10);

        jLabel11.setText("DESDE: ");
        jPanel7.add(jLabel11);

        jdcDesde1.setEnabled(false);
        jdcDesde1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jdcDesde1.setPreferredSize(new java.awt.Dimension(120, 25));
        jPanel7.add(jdcDesde1);

        jLabel12.setPreferredSize(new java.awt.Dimension(100, 0));
        jPanel7.add(jLabel12);

        jLabel13.setText("HASTA: ");
        jPanel7.add(jLabel13);

        jdcHasta1.setEnabled(false);
        jdcHasta1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jdcHasta1.setPreferredSize(new java.awt.Dimension(120, 25));
        jPanel7.add(jdcHasta1);

        jpVerCompras.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 950, 50));

        btnImpC.setText("IMPRIMIR");
        jpVerCompras.add(btnImpC, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 520, 150, 30));

        jTabbedPane2.addTab("VER COMPRAS  ", new javax.swing.ImageIcon(getClass().getResource("/iconos/bolsas-de-la-compra.png")), jpVerCompras); // NOI18N

        jpVerClientes.setBackground(new java.awt.Color(255, 255, 255));
        jpVerClientes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton6.setText("CLIENTES TOP");
        jButton6.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel5.add(jButton6);

        jButton16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton16.setText("TODOS");
        jButton16.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel5.add(jButton16);

        jpVerClientes.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 36, 950, -1));

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "COD.", "NOMBRE", "RUC", "DNI", "SEXO", "CORREO", "ESTADO"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        jpVerClientes.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 116, 950, 390));

        btnImpV3.setText("IMPRIMIR");
        jpVerClientes.add(btnImpV3, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 520, 150, 30));

        jTabbedPane2.addTab("VER CLIENTES  ", new javax.swing.ImageIcon(getClass().getResource("/iconos/subastador.png")), jpVerClientes); // NOI18N

        jpVerProductos.setBackground(new java.awt.Color(255, 255, 255));
        jpVerProductos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jpVerProductos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "COD.", "NOMBRE", "PRECIO VENTA", "STOCK", "TOTAL VENDIDO", "MONTO ACUMULADO"
            }
        ));
        jScrollPane5.setViewportView(jTable5);

        jpVerProductos.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 116, 950, 390));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jButton7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton7.setText("MAS VENDIDOS");
        jButton7.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel6.add(jButton7);

        jButton8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton8.setText("MENOS VENDIDOS");
        jButton8.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel6.add(jButton8);

        jButton17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton17.setText("TODOS");
        jButton17.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel6.add(jButton17);

        jpVerProductos.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 36, 950, -1));

        btnImpp.setText("IMPRIMIR");
        jpVerProductos.add(btnImpp, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 520, 150, 30));

        jTabbedPane2.addTab("VER PRODUCTOS  ", new javax.swing.ImageIcon(getClass().getResource("/iconos/estar-de-pie.png")), jpVerProductos); // NOI18N

        jpReportes.add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 600));

        jpMenusCards.add(jpReportes, "card4");

        jpMantenimiento.setBackground(new java.awt.Color(255, 255, 255));
        jpMantenimiento.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpClientes.setBackground(new java.awt.Color(0, 204, 153));
        jpClientes.setPreferredSize(new java.awt.Dimension(400, 150));
        jpClientes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/cliente125x125.png"))); // NOI18N
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setMaximumSize(new java.awt.Dimension(130, 130));
        jLabel1.setMinimumSize(new java.awt.Dimension(130, 130));
        jLabel1.setPreferredSize(new java.awt.Dimension(130, 130));
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jpClientes.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 130, 130));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("CLIENTES");
        jpClientes.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 220, 30));

        lblCantClientes.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblCantClientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCantClientes.setText("22");
        jpClientes.add(lblCantClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 80, 80));

        btnEntrarClientes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnEntrarClientes.setText("ENTRAR");
        btnEntrarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarClientesActionPerformed(evt);
            }
        });
        jpClientes.add(btnEntrarClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 110, 40));

        jpMantenimiento.add(jpClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, -1));

        jpProductos.setBackground(new java.awt.Color(255, 204, 0));
        jpProductos.setPreferredSize(new java.awt.Dimension(400, 150));
        jpProductos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 153, 0));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/productos125x125.png"))); // NOI18N
        jLabel22.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel22.setMaximumSize(new java.awt.Dimension(130, 130));
        jLabel22.setMinimumSize(new java.awt.Dimension(130, 130));
        jLabel22.setPreferredSize(new java.awt.Dimension(130, 130));
        jLabel22.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jpProductos.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 130, 130));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("PRODUCTOS");
        jpProductos.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 220, 30));

        lblCantProductos.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblCantProductos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCantProductos.setText("60");
        jpProductos.add(lblCantProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 80, 80));

        btnEntrarProductos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnEntrarProductos.setText("ENTRAR");
        btnEntrarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarProductosActionPerformed(evt);
            }
        });
        jpProductos.add(btnEntrarProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 110, 40));

        jpMantenimiento.add(jpProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 100, -1, -1));

        jpUsuarios.setBackground(new java.awt.Color(255, 255, 102));
        jpUsuarios.setPreferredSize(new java.awt.Dimension(400, 150));
        jpUsuarios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 153, 0));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/usuario125x125.png"))); // NOI18N
        jLabel25.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel25.setMaximumSize(new java.awt.Dimension(130, 130));
        jLabel25.setMinimumSize(new java.awt.Dimension(130, 130));
        jLabel25.setPreferredSize(new java.awt.Dimension(130, 130));
        jLabel25.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jpUsuarios.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 130, 130));

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("EMPLEADOS");
        jpUsuarios.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 220, 30));

        lblCantUsuarios.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblCantUsuarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCantUsuarios.setText("2");
        jpUsuarios.add(lblCantUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 80, 80));

        btnEntrarUsuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnEntrarUsuario.setText("ENTRAR");
        btnEntrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarUsuarioActionPerformed(evt);
            }
        });
        jpUsuarios.add(btnEntrarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 110, 40));

        jpMantenimiento.add(jpUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 340, -1, -1));

        jpProveedores.setBackground(new java.awt.Color(0, 204, 255));
        jpProveedores.setPreferredSize(new java.awt.Dimension(400, 150));
        jpProveedores.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/proveedor125x125.png"))); // NOI18N
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel5.setMaximumSize(new java.awt.Dimension(130, 130));
        jLabel5.setMinimumSize(new java.awt.Dimension(130, 130));
        jLabel5.setPreferredSize(new java.awt.Dimension(130, 130));
        jLabel5.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jpProveedores.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 130, 130));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("PROVEEDORES");
        jpProveedores.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 220, 30));

        lblCantProveedores.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblCantProveedores.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCantProveedores.setText("14");
        jpProveedores.add(lblCantProveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 80, 80));

        btnEntrarProveedor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnEntrarProveedor.setText("ENTRAR");
        btnEntrarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarProveedorActionPerformed(evt);
            }
        });
        jpProveedores.add(btnEntrarProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 110, 40));

        jpMantenimiento.add(jpProveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("MANTENIMIENTO");
        jpMantenimiento.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 840, 30));

        jpMenusCards.add(jpMantenimiento, "card2");

        jpFondo.add(jpMenusCards, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 1060, 600));

        getContentPane().add(jpFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 680));

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setMaximumSize(new java.awt.Dimension(251, 20));
        jMenuBar1.setMinimumSize(new java.awt.Dimension(251, 20));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(251, 20));

        jMenu1.setBackground(new java.awt.Color(255, 255, 255));
        jMenu1.setText("SISTEMA");
        jMenu1.setPreferredSize(new java.awt.Dimension(180, 19));

        jMenuItem1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/empleado40x40.png"))); // NOI18N
        jMenuItem1.setText("CERRAR SESIÓN");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/sistema40x40.png"))); // NOI18N
        jMenuItem2.setText("SALIR DEL SISTEMA");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("ACERCA DE");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        int opt = JOptionPane.showConfirmDialog(null, "Desea cerrar el sistema");
        if (opt == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void btnMVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMVentaActionPerformed
        cambiarCardsLayout(jpVentas);
    }//GEN-LAST:event_btnMVentaActionPerformed

    private void btnEntrarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarClientesActionPerformed
        VClientes mantCli = new VClientes();
        mantCli.setVisible(true);
    }//GEN-LAST:event_btnEntrarClientesActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        InicioSesion ini = new InicioSesion();
        ini.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btnRegistrarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarVentaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnRegistrarVentaActionPerformed

    private void btnMMantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMMantenimientoActionPerformed
        cambiarCardsLayout(jpMantenimiento);
    }//GEN-LAST:event_btnMMantenimientoActionPerformed

    private void btnMReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMReportesActionPerformed
        cambiarCardsLayout(jpReportes);
    }//GEN-LAST:event_btnMReportesActionPerformed

    private void btnMComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMComprasActionPerformed
        cambiarCardsLayout(jpCompras);
    }//GEN-LAST:event_btnMComprasActionPerformed

    private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteActionPerformed
        VClientes mantCli = new VClientes();
        mantCli.setVisible(true);
        mantCli.jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_btnBuscarClienteActionPerformed

    private void btnEntrarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarProductosActionPerformed
        VProductos mantProd = new VProductos();
        mantProd.setVisible(true);
    }//GEN-LAST:event_btnEntrarProductosActionPerformed

    private void btnEntrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarUsuarioActionPerformed
        VEmpleados mantEmp = new VEmpleados();
        mantEmp.setVisible(true);
    }//GEN-LAST:event_btnEntrarUsuarioActionPerformed

    private void btnEntrarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarProveedorActionPerformed
        VProveedor mantProv = new VProveedor();
        mantProv.setVisible(true);
    }//GEN-LAST:event_btnEntrarProveedorActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        jdcDesde.setEnabled(true);
        jdcHasta.setEnabled(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        jdcDesde1.setEnabled(true);
        jdcHasta1.setEnabled(true);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void btnBuscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProductoActionPerformed
        VProductos mantProd = new VProductos();
        mantProd.setVisible(true);
        mantProd.jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_btnBuscarProductoActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        VProveedor mantProv = new VProveedor();
        mantProv.setVisible(true);
        mantProv.jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        VProductos mantProd = new VProductos();
        mantProd.setVisible(true);
        mantProd.jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void btnRegistrarVenta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarVenta2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarVenta2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarProducto;
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton btnBuscarProducto;
    private javax.swing.JButton btnEntrarClientes;
    private javax.swing.JButton btnEntrarProductos;
    private javax.swing.JButton btnEntrarProveedor;
    private javax.swing.JButton btnEntrarUsuario;
    private javax.swing.JButton btnImpC;
    private javax.swing.JButton btnImpV;
    private javax.swing.JButton btnImpV3;
    private javax.swing.JButton btnImpp;
    private javax.swing.JButton btnMCompras;
    private javax.swing.JButton btnMMantenimiento;
    private javax.swing.JButton btnMReportes;
    private javax.swing.JButton btnMVenta;
    private javax.swing.JButton btnQuitarProducto;
    private javax.swing.JButton btnRegistrarVenta;
    private javax.swing.JButton btnRegistrarVenta2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable jTable6;
    private javax.swing.JTable jTable7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private com.toedter.calendar.JDateChooser jdcDesde;
    private com.toedter.calendar.JDateChooser jdcDesde1;
    private com.toedter.calendar.JDateChooser jdcHasta;
    private com.toedter.calendar.JDateChooser jdcHasta1;
    private javax.swing.JPanel jpBarraMenu;
    private javax.swing.JPanel jpBuscarCliente;
    private javax.swing.JPanel jpBuscarProducto;
    private javax.swing.JPanel jpClientes;
    private javax.swing.JPanel jpCompras;
    private javax.swing.JPanel jpFondo;
    private javax.swing.JPanel jpMantenimiento;
    private javax.swing.JPanel jpMenus;
    private javax.swing.JPanel jpMenusCards;
    private javax.swing.JPanel jpProductos;
    private javax.swing.JPanel jpProveedores;
    private javax.swing.JPanel jpRegistrarVenta;
    private javax.swing.JPanel jpReportes;
    private javax.swing.JPanel jpTitulo;
    private javax.swing.JPanel jpUsuarios;
    private javax.swing.JPanel jpVentas;
    private javax.swing.JPanel jpVerClientes;
    private javax.swing.JPanel jpVerCompras;
    private javax.swing.JPanel jpVerProductos;
    private javax.swing.JPanel jpVerVentas;
    private javax.swing.JLabel lblCantClientes;
    private javax.swing.JLabel lblCantProductos;
    private javax.swing.JLabel lblCantProveedores;
    private javax.swing.JLabel lblCantUsuarios;
    private javax.swing.JLabel lblCopy1;
    private javax.swing.JLabel lblCopy2;
    private javax.swing.JLabel lblFechaAuto;
    public static javax.swing.JLabel lblHoraAuto;
    private javax.swing.JLabel lblNBoleta;
    private javax.swing.JLabel lblTipoEmpleado;
    private javax.swing.JTextField txtMontoTotal;
    private javax.swing.JTextField txtMontoTotal1;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtNombreProducto;
    private javax.swing.JTextField txtPrecioProd;
    private javax.swing.JTextField txtStockPro;
    // End of variables declaration//GEN-END:variables

    private void cambiarCardsLayout(JPanel panel) {
        jpMenusCards.removeAll();
        jpMenusCards.repaint();
        jpMenusCards.revalidate();

        jpMenusCards.add(panel);
        jpMenusCards.repaint();
        jpMenusCards.revalidate();
    }

}
